# Generated by Django 5.0.6 on 2024-05-21 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PetBehavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('behavior', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_email', models.EmailField(max_length=254)),
                ('date_added', models.DateTimeField()),
                ('pet_age', models.IntegerField()),
                ('pet_breed', models.CharField(max_length=100)),
                ('pet_color', models.CharField(max_length=100)),
                ('pet_description', models.TextField()),
                ('pet_favorite_snack', models.CharField(max_length=100)),
                ('pet_image_url', models.URLField()),
                ('pet_name', models.CharField(max_length=100)),
                ('pet_behavior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_behavior_posts', to='api.petbehavior')),
            ],
        ),
    ]
